package business.model;
// Generated Jan 25, 2016 2:05:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Trackday generated by hbm2java
 */
public class Trackday  implements java.io.Serializable {


     private Integer tdId;
     private Track track;
     private Date tdDate;
     private String level;
     private String racecat;
     private String pricing;
     private int maxDrivers;
     private String safety;
     private String tdUrl;
     private Set tdlists = new HashSet(0);

    public Trackday() {
    }

	
    public Trackday(Track track, Date tdDate, String level, String racecat, String pricing, int maxDrivers, String safety, String tdUrl) {
        this.track = track;
        this.tdDate = tdDate;
        this.level = level;
        this.racecat = racecat;
        this.pricing = pricing;
        this.maxDrivers = maxDrivers;
        this.safety = safety;
        this.tdUrl = tdUrl;
    }
    public Trackday(Track track, Date tdDate, String level, String racecat, String pricing, int maxDrivers, String safety, String tdUrl, Set tdlists) {
       this.track = track;
       this.tdDate = tdDate;
       this.level = level;
       this.racecat = racecat;
       this.pricing = pricing;
       this.maxDrivers = maxDrivers;
       this.safety = safety;
       this.tdUrl = tdUrl;
       this.tdlists = tdlists;
    }
   
    public Integer getTdId() {
        return this.tdId;
    }
    
    public void setTdId(Integer tdId) {
        this.tdId = tdId;
    }
    public Track getTrack() {
        return this.track;
    }
    
    public void setTrack(Track track) {
        this.track = track;
    }
    public Date getTdDate() {
        return this.tdDate;
    }
    
    public void setTdDate(Date tdDate) {
        this.tdDate = tdDate;
    }
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    public String getRacecat() {
        return this.racecat;
    }
    
    public void setRacecat(String racecat) {
        this.racecat = racecat;
    }
    public String getPricing() {
        return this.pricing;
    }
    
    public void setPricing(String pricing) {
        this.pricing = pricing;
    }
    public int getMaxDrivers() {
        return this.maxDrivers;
    }
    
    public void setMaxDrivers(int maxDrivers) {
        this.maxDrivers = maxDrivers;
    }
    public String getSafety() {
        return this.safety;
    }
    
    public void setSafety(String safety) {
        this.safety = safety;
    }
    public String getTdUrl() {
        return this.tdUrl;
    }
    
    public void setTdUrl(String tdUrl) {
        this.tdUrl = tdUrl;
    }
    public Set getTdlists() {
        return this.tdlists;
    }
    
    public void setTdlists(Set tdlists) {
        this.tdlists = tdlists;
    }




}


