package business;
// Generated Jan 25, 2016 2:05:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tduser generated by hbm2java
 */
public class Tduser  implements java.io.Serializable {


     private Integer userId;
     private String login;
     private String password;
     private String firstname;
     private String lastname;
     private String email;
     private boolean userActivated;
     private Set tracks = new HashSet(0);
     private Set tdlists = new HashSet(0);

    public Tduser() {
    }

	
    public Tduser(String login, String password, String firstname, String lastname, String email, boolean userActivated) {
        this.login = login;
        this.password = password;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.userActivated = userActivated;
    }
    public Tduser(String login, String password, String firstname, String lastname, String email, boolean userActivated, Set tracks, Set tdlists) {
       this.login = login;
       this.password = password;
       this.firstname = firstname;
       this.lastname = lastname;
       this.email = email;
       this.userActivated = userActivated;
       this.tracks = tracks;
       this.tdlists = tdlists;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isUserActivated() {
        return this.userActivated;
    }
    
    public void setUserActivated(boolean userActivated) {
        this.userActivated = userActivated;
    }
    public Set getTracks() {
        return this.tracks;
    }
    
    public void setTracks(Set tracks) {
        this.tracks = tracks;
    }
    public Set getTdlists() {
        return this.tdlists;
    }
    
    public void setTdlists(Set tdlists) {
        this.tdlists = tdlists;
    }




}


